"""ajustar cpf de pacientes

Revision ID: 8a9f79d636c5
Revises: f31a7fbf3e90
Create Date: 2026-10-06 12:44:27.777925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a9f79d636c5'
down_revision: Union[str, Sequence[str], None] = 'f31a7fbf3e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'cpf',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'cpf',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=True)
    # ### end Alembic commands ###
