"""ajustar telefone de pacientes

Revision ID: 999dab4a9324
Revises: 4874d791fda4
Create Date: 2026-10-07 10:35:49.525913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '999dab4a9324'
down_revision: Union[str, Sequence[str], None] = '4874d791fda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'telefone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'telefone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
